package com.zorro.videodl.cookie

import android.content.Context
import android.util.Log
import android.webkit.CookieManager
import com.zorro.videodl.core.SiteHandler
import java.io.File
import java.net.URI

/**
 * Bridges Android's WebView cookie jar to the Netscape cookies.txt file that
 * yt-dlp's `--cookies` flag expects. One file per site keeps a broken login on
 * one service from poisoning the others.
 */
object CookieStore {

    private fun dir(context: Context): File =
        File(context.filesDir, "cookies").apply { mkdirs() }

    fun fileFor(context: Context, siteId: String): File = File(dir(context), "$siteId.txt")

    fun hasCookies(context: Context, siteId: String): Boolean =
        fileFor(context, siteId).let { it.exists() && it.length() > 0 }

    /** Cookie file for the site, or null when nothing has been captured yet. */
    fun cookieFileOrNull(context: Context, siteId: String): File? =
        fileFor(context, siteId).takeIf { it.exists() && it.length() > 0 }

    fun clear(context: Context, siteId: String) {
        fileFor(context, siteId).delete()
    }

    /**
     * Harvests every cookie the WebView holds for the handler's domains and
     * writes them out. Returns the number of cookies captured.
     */
    fun captureFromWebView(context: Context, handler: SiteHandler): Int {
        val manager = CookieManager.getInstance()
        // Session cookies live only in memory until this runs.
        manager.flush()

        val lines = mutableListOf<String>()
        // Far-future expiry: yt-dlp drops anything already expired, and the real
        // lifetime is enforced by the server rejecting a stale session anyway.
        val expiry = (System.currentTimeMillis() / 1000) + 60L * 60 * 24 * 365

        handler.cookieDomains.forEach { domain ->
            val bareDomain = domain.trimStart('.')
            // A cookie set with an exact-host scope (e.g. only on www.instagram.com,
            // no leading dot) is invisible to a query against the bare apex domain.
            // Query every host this login could plausibly have scoped cookies to and
            // merge by name, rather than gambling on which form the site used.
            val hosts = buildSet {
                add(bareDomain)
                add("www.$bareDomain")
                runCatching { URI(handler.loginUrl).host }.getOrNull()?.let { add(it) }
            }

            val seen = LinkedHashMap<String, String>() // cookie name -> value, first host wins
            hosts.forEach { host ->
                val raw = manager.getCookie("https://$host") ?: return@forEach
                raw.split(';').forEach { pair ->
                    val name = pair.substringBefore('=').trim()
                    val value = pair.substringAfter('=', "").trim()
                    if (name.isNotEmpty()) seen.putIfAbsent(name, value)
                }
            }

            Log.d(
                "CookieStore",
                "${handler.id}: queried ${hosts.joinToString()} -> captured ${seen.keys.joinToString()}",
            )

            seen.forEach { (name, value) ->
                val includeSubdomains = if (domain.startsWith(".")) "TRUE" else "FALSE"
                lines += listOf(domain, includeSubdomains, "/", "FALSE", expiry.toString(), name, value)
                    .joinToString("\t")
            }
        }

        val out = fileFor(context, handler.id)
        if (lines.isEmpty()) {
            out.delete()
            return 0
        }
        out.writeText(
            buildString {
                appendLine("# Netscape HTTP Cookie File")
                appendLine("# Generated by VideoDownloader")
                lines.forEach { appendLine(it) }
            }
        )
        return lines.size
    }

    /**
     * Expires every cookie the WebView holds for this handler's domains, so the
     * next login screen actually starts signed out.
     *
     * Deleting the cookies.txt file alone is not a logout: yt-dlp stops seeing
     * the session, but the WebView keeps its own jar, so reopening the login
     * screen lands straight back on a signed-in page. Android exposes no
     * per-cookie delete — overwriting with an already-expired cookie is the
     * supported way — and it has to be done twice per name, because a
     * host-scoped cookie and a domain-scoped one are separate entries.
     *
     * Scoped to one site on purpose: [CookieManager.removeAllCookies] would
     * sign the user out of every other site's WebView session too.
     */
    fun clearWebViewCookies(handler: SiteHandler) {
        val manager = CookieManager.getInstance()
        val expired = "Expires=Thu, 01 Jan 1970 00:00:00 GMT"

        handler.cookieDomains.forEach { domain ->
            val bareDomain = domain.trimStart('.')
            val hosts = buildSet {
                add(bareDomain)
                add("www.$bareDomain")
                runCatching { URI(handler.loginUrl).host }.getOrNull()?.let { add(it) }
            }
            hosts.forEach { host ->
                val url = "https://$host"
                val raw = manager.getCookie(url) ?: return@forEach
                raw.split(';')
                    .map { it.substringBefore('=').trim() }
                    .filter { it.isNotEmpty() }
                    .forEach { name ->
                        manager.setCookie(url, "$name=; Path=/; $expired")
                        manager.setCookie(url, "$name=; Path=/; Domain=.$bareDomain; $expired")
                    }
            }
        }
        manager.flush()
    }
}
